name: Build and deploy to remote server

on:
  push:
    branches: [ "main" ]
    
env:
  image_tag: ${{ secrets.DOCKERHUB_USERNAME }}/pray:latest
  container_name: pray

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ env.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - 
        name: Update container version via SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ env.image_tag }}
            docker stop ${{ env.container_name }} || true && docker rm ${{ env.container_name }} || true
            docker run -d --name ${{ env.container_name }}  --env \
              ConnectionString="${{ secrets.DB }}" \
              FirebaseSecret="${{ secretes.FIREBASE }}" \
              Vk__Token="${{ secretes.VK_TOKEN }}" \
              AdminAuth__Login="${{ secrets.ADMIN_LOGIN }}"\
              AdminAuth__Password="${{ secrets.ADMIN_PASSWORD }}"\
              -p ${{ secrets.APP_PORT }}:80 ${{ env.image_tag }} 
